### ISSUE TITLE
Need to create way to see if PR improves results on a dataset

### ISSUE THREAD

**Issue by johnwlambert** [borglab/gtsfm#109]
We need to create a way to see if a PR improves results on a dataset (or suite of small datasets).

Perhaps via publishing an artifact? And storing the previous best results in a special file location somewhere?

@ProfFan @akshay-krishnan @ayushbaid any thoughts on how we should do this?

**Comment by johnwlambert** [comment]
- Do some research about how this is done in other projects.
(tentatively Akshay is taking this up)

**Comment by johnwlambert** [comment]
A temporary solution to aggregating metrics is `log_sfm_summary()` inside `gtsfm/utils/metrics.py`

However, hardcoding the metrics names there is hacky. If we change the metric in a module we have to change all this. So some or the key value pairs in a metrics dictionary are currently very verbose and not informative.

We need to come up with a more long term solution for printing out the summary statistics of interest with a generic metric class. The organization of the metric in the dictionary should be structured so that we can print any dictionary?

**Comment by ProfFan** [comment]
FYI, there are 20 hanging PRs. I would suggest the following:
1. Fix CI on master
2. add simple metrics CI. (https://docs.github.com/en/rest/reference/checks#create-a-check-run)
2. merge them one by one (or drop)
3. do other stuff
