### ISSUE TITLE
Make sure that we store the camera pose world coordinates (wTc) instead of the completely un-intuitive and bug-prone "world to camera" transform (cTw) 

### ISSUE THREAD

**Issue by ayushbaid** [borglab/gtsfm#119]
I have been using `wTc`, which is not preferred. This needs to be changed everywhere in GTSFM.

**Comment by johnwlambert** [comment]
Hmm I dont follow @ayushbaid  -- wTc is preferred for pose, since translation immediately gives us a point in the world frame

**Comment by dellaert** [comment]
To be clear, `wTc` is the one I prefer, and it transforms points `cP` in camera frame to points `wP` in the world frame. The columns of `wRc` are the axes of the camera, expressed in the world frame. And as John says, the translation part is directly the position of the camera, in the world frame.

I am being explicit (almost pedantic) as I have seen smart student reverse the meaning of the convention in their heads.

**Comment by dellaert** [comment]
I am going to rename this issue to make sure someone does not inadvertently execute on the wrong course of action.

**Comment by ayushbaid** [comment]
Oh ok. Damn I got it flipped in my head again today. Everywhere I have used `wTc`, but today I thought we need to use `cTw`. I'll check it again throughout the code and close this issue.

**Comment by johnwlambert** [comment]
Closing this for now -- we use `wTc` everywhere I've seen in the codebase for camera poses.
