### ISSUE TITLE
Provide functionality in GtsfmData to compute min and max distances for MVS depth

### ISSUE THREAD

**Issue by johnwlambert** [borglab/gtsfm#128]
Add method in SFMResult or GtsfmData that returns
-  (1) point cloud
- (2) min distance from any camera to any 3d point
- (3) min distance from any camera to any 3d point

**Comment by johnwlambert** [comment]
Assigned to @codyly  currently

**Comment by johnwlambert** [comment]
@codyly can we go ahead and close this, or is this still something you think we need?

**Comment by codyly** [comment]
> @codyly can we go ahead and close this, or is this still something you think we need?

We can close it. I think it has been implemented in the current workflow.
