### ISSUE TITLE
Subtree vs. submodule for externally licensed code

### ISSUE THREAD

**Issue by johnwlambert** [borglab/gtsfm#140]

**Comment by johnwlambert** [comment]
@ProfFan do you have any suggestions on which is preferred?

**Comment by ProfFan** [comment]
I personally prefer dependency rather than vendoring, if possible.

**Comment by dellaert** [comment]
@ProfFan Explain this please????

**Comment by ProfFan** [comment]
@dellaert I mean if it is possible to make external code a dependency (not in our repo) it's better to just make it a dependency.

However, if it's something that needs to be vendored (put inside our repo) then it's better to download a tarball, unzip to a `3rdparty` folder, and commit the 3rd party code as a big commit. This is what we have done in GTSAM too.

**Comment by ayushbaid** [comment]
@johnwlambert has copied over the code manually.
