### ISSUE TITLE
MVS densify results can vary a lot among different runs

### ISSUE THREAD

**Issue by codyly** [borglab/gtsfm#150]
In general runs, the dense point cloud will have about 1e6 points, but sometimes the number will be less than 1e3.

**Comment by akshay-krishnan** [comment]
@codyly could you update the status of this issue?

**Comment by johnwlambert** [comment]
Hi @codyly, was this resolved, or is still an issue? What dataset did you observe this on?

**Comment by codyly** [comment]
The issue was based on the door dataset for previous implementations (in April 2021). There is no problem now
