### ISSUE TITLE
Skydio Crane Tower Reconstruction

### ISSUE THREAD

**Issue by womackj1** [borglab/gtsfm#161]
Metrics:
[2021-04-23 12:32:54,514 INFO sfm_track.py line 173 70703] DSF Union-Find: 1.19% of tracks discarded from multiple obs. in a single image.
[2021-04-23 12:35:16,131 DEBUG data_assoc.py line 87 70703] [Data association] input number of tracks: 5397
[2021-04-23 12:35:16,131 DEBUG data_assoc.py line 88 70703] [Data association] input avg. track length: 2.7196590698536225
[2021-04-23 12:35:16,999 INFO gtsfm_data.py line 211 70703] Largest connected component contains 11 of 11 cameras returned by front-end (of 11 total imgs)
[2021-04-23 12:35:17,011 DEBUG data_assoc.py line 133 70703] [Data association] output number of tracks: 1215
[2021-04-23 12:35:17,011 DEBUG data_assoc.py line 134 70703] [Data association] output avg. track length: 2.09
[2021-04-23 12:35:17,102 INFO bundle_adjustment.py line 43 70703] Input: 1215 tracks on 11 cameras

[2021-04-23 12:35:17,636 INFO bundle_adjustment.py line 108 70703] initial error: 2761678.19
[2021-04-23 12:35:17,636 INFO bundle_adjustment.py line 109 70703] final error: 2761678.19
[2021-04-23 12:35:17,690 INFO bundle_adjustment.py line 114 70703] [Result] Number of tracks before filtering 1215
[2021-04-23 12:35:17,773 INFO bundle_adjustment.py line 119 70703] [Result] Number of tracks after filtering: 42
[2021-04-23 12:35:17,774 INFO bundle_adjustment.py line 121 70703] [Result] Mean track length 2.000
[2021-04-23 12:35:17,776 INFO bundle_adjustment.py line 122 70703] [Result] Median track length 2.000
[2021-04-23 12:35:17,778 INFO gtsfm_data.py line 277 70703] Min scene reproj error: 0.007
[2021-04-23 12:35:17,779 INFO gtsfm_data.py line 278 70703] Avg scene reproj error: 1.203
[2021-04-23 12:35:17,780 INFO gtsfm_data.py line 279 70703] Median scene reproj error: 1.062
[2021-04-23 12:35:17,781 INFO gtsfm_data.py line 280 70703] Max scene reproj error: 2.751

Plots:
![3d](https://user-images.githubusercontent.com/46657985/115902768-c676ec00-a430-11eb-83b4-3a0bdf88b177.png)
![bev](https://user-images.githubusercontent.com/46657985/115902770-c70f8280-a430-11eb-809f-64c3cc849227.png)
![poses_3d](https://user-images.githubusercontent.com/46657985/115902772-c70f8280-a430-11eb-85e4-20ef885c42d7.png)
![poses_bev](https://user-images.githubusercontent.com/46657985/115902773-c70f8280-a430-11eb-9cbc-837c9a3cbe7f.png)

Dataset:
![DSC_0001](https://user-images.githubusercontent.com/46657985/115899496-cd9bfb00-a42c-11eb-9225-2bb53005b6e7.JPG)
![DSC_0002](https://user-images.githubusercontent.com/46657985/115899497-ce349180-a42c-11eb-8425-0087a419e951.JPG)
![DSC_0003](https://user-images.githubusercontent.com/46657985/115899499-cecd2800-a42c-11eb-8eea-19bb0d6a0caa.JPG)
![DSC_0004](https://user-images.githubusercontent.com/46657985/115899500-cecd2800-a42c-11eb-9dd0-24c43bc77b98.JPG)
![DSC_0005](https://user-images.githubusercontent.com/46657985/115899503-cecd2800-a42c-11eb-9ed8-dbc01d9f529b.JPG)
![DSC_0006](https://user-images.githubusercontent.com/46657985/115899505-cf65be80-a42c-11eb-8929-15a3b2569632.JPG)
![DSC_0007](https://user-images.githubusercontent.com/46657985/115899507-cf65be80-a42c-11eb-82bd-1beb31835b81.JPG)
![DSC_0008](https://user-images.githubusercontent.com/46657985/115902680-ad6e3b00-a430-11eb-9e5c-227f4282d30a.JPG)
![DSC_0009](https://user-images.githubusercontent.com/46657985/115902687-ae9f6800-a430-11eb-8413-9109462b04fc.JPG)
![DSC_0010](https://user-images.githubusercontent.com/46657985/115902690-af37fe80-a430-11eb-81a7-6f19fe00660e.JPG)
![DSC_0011](https://user-images.githubusercontent.com/46657985/115902695-afd09500-a430-11eb-9daf-33790fd98d07.JPG)

**Comment by johnwlambert** [comment]
Hi @womackj1, thanks for sharing this.

It looks like Bundle ADjustment is basically a no-op here, with error unchanged. Can you share what the 2-image correspondences look like,and what some of the track patches look like? (two settings to set to True in the config)

**Comment by womackj1** [comment]
Here are the plots:

![0_1](https://user-images.githubusercontent.com/46657985/115948434-67e75780-a49c-11eb-9c6a-c7ce354259eb.jpg)
![0_2](https://user-images.githubusercontent.com/46657985/115948435-67e75780-a49c-11eb-99d3-8d5ce7a92746.jpg)
![0_3](https://user-images.githubusercontent.com/46657985/115948436-687fee00-a49c-11eb-8f4e-a245a6937b1b.jpg)
![0_4](https://user-images.githubusercontent.com/46657985/115948437-687fee00-a49c-11eb-8953-c9163056d80c.jpg)
![0_5](https://user-images.githubusercontent.com/46657985/115948438-687fee00-a49c-11eb-9cf0-15cd8ee40a1b.jpg)
![0_6](https://user-images.githubusercontent.com/46657985/115948439-687fee00-a49c-11eb-8899-10bb1aed180e.jpg)
![0_7](https://user-images.githubusercontent.com/46657985/115948440-69188480-a49c-11eb-9065-d5c3aa240b77.jpg)
![0_8](https://user-images.githubusercontent.com/46657985/115948441-69188480-a49c-11eb-8d70-7a44c54fde41.jpg)
![0_9](https://user-images.githubusercontent.com/46657985/115948442-69188480-a49c-11eb-9dca-3b0e914a19b6.jpg)
![0_10](https://user-images.githubusercontent.com/46657985/115948443-69b11b00-a49c-11eb-9769-228af490c594.jpg)
![1_2](https://user-images.githubusercontent.com/46657985/115948444-69b11b00-a49c-11eb-8f74-8599072b85f9.jpg)
![1_3](https://user-images.githubusercontent.com/46657985/115948445-69b11b00-a49c-11eb-96f2-55982d34ade2.jpg)
![1_4](https://user-images.githubusercontent.com/46657985/115948446-69b11b00-a49c-11eb-8df6-60b2d21eadb6.jpg)
![1_5](https://user-images.githubusercontent.com/46657985/115948447-6a49b180-a49c-11eb-9a2f-04ce96b08184.jpg)
![1_6](https://user-images.githubusercontent.com/46657985/115948448-6a49b180-a49c-11eb-8c52-601285c92515.jpg)
![1_7](https://user-images.githubusercontent.com/46657985/115948449-6a49b180-a49c-11eb-85b3-0b0a406aadd5.jpg)
![1_8](https://user-images.githubusercontent.com/46657985/115948450-6ae24800-a49c-11eb-9924-8b51e2aeef9a.jpg)
![1_9](https://user-images.githubusercontent.com/46657985/115948453-6ae24800-a49c-11eb-9c3b-adf06946b39b.jpg)
![1_10](https://user-images.githubusercontent.com/46657985/115948454-6ae24800-a49c-11eb-8d42-f69cc80ad31c.jpg)
![2_3](https://user-images.githubusercontent.com/46657985/115948455-6b7ade80-a49c-11eb-9a15-ea18acb223eb.jpg)
![2_4](https://user-images.githubusercontent.com/46657985/115948456-6b7ade80-a49c-11eb-8a86-bcd8782b5079.jpg)
![2_5](https://user-images.githubusercontent.com/46657985/115948457-6b7ade80-a49c-11eb-9aab-d98c94b73e95.jpg)
![2_6](https://user-images.githubusercontent.com/46657985/115948458-6b7ade80-a49c-11eb-88b7-72d0d6e9bb4b.jpg)
![2_7](https://user-images.githubusercontent.com/46657985/115948459-6c137500-a49c-11eb-936b-ca2b94d19efa.jpg)
![2_8](https://user-images.githubusercontent.com/46657985/115948460-6c137500-a49c-11eb-9d4d-c40012e3d9f6.jpg)
![2_9](https://user-images.githubusercontent.com/46657985/115948461-6c137500-a49c-11eb-8b60-c1d8bbad640d.jpg)
![2_10](https://user-images.githubusercontent.com/46657985/115948462-6cac0b80-a49c-11eb-86c5-e12bf1753f6c.jpg)
![3_4](https://user-images.githubusercontent.com/46657985/115948463-6cac0b80-a49c-11eb-9222-1609c7ada642.jpg)
![3_5](https://user-images.githubusercontent.com/46657985/115948464-6cac0b80-a49c-11eb-96b6-1a8dd80dfb12.jpg)
![3_6](https://user-images.githubusercontent.com/46657985/115948465-6d44a200-a49c-11eb-932a-869de9470794.jpg)
![3_7](https://user-images.githubusercontent.com/46657985/115948466-6d44a200-a49c-11eb-8570-d7cceb800932.jpg)
![3_8](https://user-images.githubusercontent.com/46657985/115948468-6ddd3880-a49c-11eb-969b-09b6765426b1.jpg)
![3_9](https://user-images.githubusercontent.com/46657985/115948469-6ddd3880-a49c-11eb-88a4-d0c59ee5a744.jpg)
![3_10](https://user-images.githubusercontent.com/46657985/115948470-6ddd3880-a49c-11eb-8246-36fdb161f270.jpg)
![4_5](https://user-images.githubusercontent.com/46657985/115948471-6e75cf00-a49c-11eb-84ae-ce77e7171d0d.jpg)
![4_6](https://user-images.githubusercontent.com/46657985/115948472-6e75cf00-a49c-11eb-9f46-3cbd55406199.jpg)
![4_7](https://user-images.githubusercontent.com/46657985/115948473-6e75cf00-a49c-11eb-8854-2a37ee9cd80b.jpg)
![4_8](https://user-images.githubusercontent.com/46657985/115948474-6e75cf00-a49c-11eb-9a9f-ff507a9b6508.jpg)
![4_9](https://user-images.githubusercontent.com/46657985/115948475-6f0e6580-a49c-11eb-93a6-eec78f8226e6.jpg)
![4_10](https://user-images.githubusercontent.com/46657985/115948476-6f0e6580-a49c-11eb-9578-bedfd3834c5b.jpg)
![5_6](https://user-images.githubusercontent.com/46657985/115948477-6f0e6580-a49c-11eb-8434-54d6ef5612e0.jpg)
![5_7](https://user-images.githubusercontent.com/46657985/115948478-6f0e6580-a49c-11eb-9735-cb483e87b38d.jpg)
![5_8](https://user-images.githubusercontent.com/46657985/115948479-6fa6fc00-a49c-11eb-84f0-f7a341ebacc1.jpg)
![5_9](https://user-images.githubusercontent.com/46657985/115948480-6fa6fc00-a49c-11eb-96cc-aacd08c73e3f.jpg)
![5_10](https://user-images.githubusercontent.com/46657985/115948483-6fa6fc00-a49c-11eb-87f5-4f92ce4cee44.jpg)
![6_7](https://user-images.githubusercontent.com/46657985/115948484-6fa6fc00-a49c-11eb-94d8-8e86320d5579.jpg)
![6_8](https://user-images.githubusercontent.com/46657985/115948485-703f9280-a49c-11eb-937c-c82542784cb2.jpg)
![6_9](https://user-images.githubusercontent.com/46657985/115948487-703f9280-a49c-11eb-8e22-6aa9061c55dd.jpg)
![6_10](https://user-images.githubusercontent.com/46657985/115948488-703f9280-a49c-11eb-912f-43d412203a02.jpg)
![7_8](https://user-images.githubusercontent.com/46657985/115948489-703f9280-a49c-11eb-854d-38baa3efa466.jpg)
![7_9](https://user-images.githubusercontent.com/46657985/115948490-70d82900-a49c-11eb-999f-4d8bc13afcec.jpg)
![7_10](https://user-images.githubusercontent.com/46657985/115948491-70d82900-a49c-11eb-9d9d-ef7cb290bf32.jpg)
![8_9](https://user-images.githubusercontent.com/46657985/115948493-70d82900-a49c-11eb-8df8-e5441784254c.jpg)
![8_10](https://user-images.githubusercontent.com/46657985/115948494-7170bf80-a49c-11eb-8dd9-b5944a56cf0f.jpg)
![9_10](https://user-images.githubusercontent.com/46657985/115948496-7170bf80-a49c-11eb-8a8f-a54fe45f54d3.jpg)

**Comment by womackj1** [comment]
Here are a few track patches:
![track_0](https://user-images.githubusercontent.com/46657985/115948538-ae3cb680-a49c-11eb-853b-4ca286b4e88c.jpg)
![track_123](https://user-images.githubusercontent.com/46657985/115948539-ae3cb680-a49c-11eb-9751-37f80633e6d5.jpg)
![track_226](https://user-images.githubusercontent.com/46657985/115948540-ae3cb680-a49c-11eb-8400-982acef4ce78.jpg)
![track_338](https://user-images.githubusercontent.com/46657985/115948541-ae3cb680-a49c-11eb-9633-1e82cc6319a2.jpg)
![track_480](https://user-images.githubusercontent.com/46657985/115948542-ae3cb680-a49c-11eb-8837-b3012d86337f.jpg)
![track_627](https://user-images.githubusercontent.com/46657985/115948543-ae3cb680-a49c-11eb-8bc2-ef4d2045dafc.jpg)
![track_819](https://user-images.githubusercontent.com/46657985/115948544-aed54d00-a49c-11eb-98e0-a28160ba4b26.jpg)
![track_1012](https://user-images.githubusercontent.com/46657985/115948545-aed54d00-a49c-11eb-944d-61242247f5bb.jpg)
![track_1168](https://user-images.githubusercontent.com/46657985/115948546-aed54d00-a49c-11eb-97d0-80e031eb6b23.jpg)
![track_1334](https://user-images.githubusercontent.com/46657985/115948547-aed54d00-a49c-11eb-838e-906d0290f72c.jpg)
![track_1498](https://user-images.githubusercontent.com/46657985/115948548-aed54d00-a49c-11eb-9e40-a26b5f2ac2d4.jpg)
![track_1824](https://user-images.githubusercontent.com/46657985/115948549-aed54d00-a49c-11eb-8b37-365ca7e05c04.jpg)
![track_1978](https://user-images.githubusercontent.com/46657985/115948550-aed54d00-a49c-11eb-822d-f02c7dd75ae0.jpg)
![track_2239](https://user-images.githubusercontent.com/46657985/115948551-af6de380-a49c-11eb-84e1-6d8d0ac24fc8.jpg)
![track_2305](https://user-images.githubusercontent.com/46657985/115948553-af6de380-a49c-11eb-8efa-206657caddb6.jpg)
![track_2561](https://user-images.githubusercontent.com/46657985/115948554-af6de380-a49c-11eb-83d7-43ce477338c2.jpg)

**Comment by dellaert** [comment]
The correspondences are great in many cases but quite sparse. This reminds me of the tree data sets as well. We’re over-indexing on the background. It seems very at odds with all the deep neural network paper results. @ayushbaid

**Comment by ayushbaid** [comment]
Agreed. Maybe superglue is worth trying on this dataset.

Or we need to recover more correspondences after we get the two-view relative pose.
