### ISSUE TITLE
Link to gtsam.4.1.1 wheel broken

### ISSUE THREAD

**Issue by nickponline** [borglab/gtsfm#193]
The links from the README to gtsam-4.1.1-py3-none-any.whl don't work.

**Comment by johnwlambert** [comment]
Hi @nickponline, thanks for your interest in our work and for catching this. You can use any of the wheels listed under "Artifacts" here: https://github.com/borglab/gtsam-manylinux-build/actions/runs/952573978

Best,
John

**Comment by nickponline** [comment]
Thanks @johnwlambert  appreciate the response will check it out.

**Comment by johnwlambert** [comment]
Closing since I think this was resolved; please re-open if not
