### ISSUE TITLE
Update benchmarking datasets

### ISSUE THREAD

**Issue by travisdriver** [borglab/gtsfm#266]
I'm not sure it's valid to draw any conclusions from a single datapoint. What about the other benchmarks? If you think the other benchmarks are not sufficient for evaluating the performance of gtsfm, then we should be using other datasets.

In general, I think we need to graduate from the single (and even double) digit length image sequences. I also think we need to inject more variability into the datasets, as there are only two different scenes being used for benchmarking. Maybe we could also add some argoverse and AstroNet datasets for benchmarking.

_Originally posted by @travisdriver in https://github.com/borglab/gtsfm/issues/260#issuecomment-913734286_

**Comment by ayushbaid** [comment]
We have an astronet sequence, as well as other large sequences. Closing this for now.
