### ISSUE TITLE
Visualize two separate pathways in the process graph

### ISSUE THREAD

**Issue by kfu02** [borglab/gtsfm#550]
Issue: process graph currently only accounts for one possible pathway through GTSFM, though there are now two:

> By the way, we now support methods that generate matches directly from images (without descriptors). So technically there are two possible graphs now, or two separate pathways, because of the CorrespondenceGenerator. @ayushbaid @akshaykrishnan @dellaert any thoughts about how to visualize  that?

_Originally posted by @johnwlambert in https://github.com/borglab/gtsfm/issues/540#issuecomment-1221454357_

**Comment by johnwlambert** [comment]
Fixd by https://github.com/borglab/gtsfm/pull/561
