### ISSUE TITLE
Make and model not found in the database

### ISSUE THREAD

**Issue by quicktwit** [borglab/gtsfm#560]
Hi
I am really excited to use this repo for my work. Thank you to all the authors.
I have an issue:
I am getting this error "Make and model not found in the database" even though it is available in the csv (https://github.com/borglab/gtsfm/blob/master/assets/camera_details/sensor_database.csv#L702).

I checked the images and exif is embedded.

I ran the script like this:
`python gtsfm/runner/run_scene_optimizer_olssonloader.py --dataset_root samples/dataset/ --image_extension JPG --config_name deep_front_end.yaml --num_workers 4`
Can someone help what I am doing wrong or any suggestion would be appreciated. Thank you!

Note: 
PC Specs:
Ubuntu 20.04

**Comment by womackj1** [comment]
Hi Alok,

Could you check to see that the exif's Make and Model match the entry in the database?

You could do this manually or by logging `self.exif_data.get("Make")` and `self.exif_data.get("Model")` immediately before line 56 in  gtsfm/common/image.py.

**Comment by quicktwit** [comment]
Hi @womackj1 
Thank you for your reply.
I added print before line 56 and I get these:
exif data Make = DJI
exif data Model = FC6310
I can parse the make and model, but still getting error. 
![Screen Shot 2022-10-25 at 11 54 35](https://user-images.githubusercontent.com/4423688/197671334-db67b8b1-0881-4139-8398-d64cc50a2118.png)

**Comment by akshay-krishnan** [comment]
That is weird, @quicktwit please share a stack trace and which version of code you are running. 

I made a colab here that cross-checks your use case: https://colab.research.google.com/drive/1LzYWz0EQ4CSvCIwD4dgLW1x9bqZK1_Gb?usp=sharing. It gives the right answer "6.17". 

I do find one problem in that code `if len(selected) != 1` should be replaced with `if len(selected) == 0`, but this should not affect your use case.

**Comment by akshay-krishnan** [comment]
The exact error message would also tell the actual make and model being passed in, so a trace would help!

**Comment by quicktwit** [comment]
Hi @akshay-krishnan 
Somehow, when I did git clone again after removing previous version, then I get no error. I will close this issue for now. Thank you everyone 🙇
