### ISSUE TITLE
NetVLAD does not use delayed images, fails on cluster

### ISSUE THREAD

**Issue by akshay-krishnan** [borglab/gtsfm#630]
The retriever API accepts a loader. NetVLAD calls loader.get_image(), loading images synchronously. The API needs to be updated to use delayed images to be run on a cluster.

**Comment by akshay-krishnan** [comment]
cc @stepanyanhayk

**Comment by akshay-krishnan** [comment]
I think this needs more thought @stepanyanhayk . 

If we can pass delayed images to the retriever, this function will be the one where the images are actually loaded into memory: https://github.com/borglab/gtsfm/blob/4a9dc6a7ae9a1146b3fc056827b265776921b49c/gtsfm/retriever/netvlad_retriever.py#L120
That function is wrapped with a delayed. We cannot create another delayed operation within it (for a delayed per-image loading), because dask does not play well with nested delayed functions I think. 
So one option (I think a nice one) is to simply pass the images as arguments to that function, two lists of images for that block will need to be loaded into memory at once, which might work with a smaller block size. This also allows us to run the netvlad model for all images as a batch, instead of batch_size=1 which we do now.

**Comment by akshay-krishnan** [comment]
cc @johnwlambert for a similar discussion I had with him offline

**Comment by travisdriver** [comment]
Has this been addressed?

**Comment by ayushbaid** [comment]
#636 will address it
