### ISSUE TITLE
3d visualizer

### ISSUE THREAD

**Issue by johnwlambert** [borglab/gtsfm#68]
Need a better 3d visualizer e.g. Pangolin and make sure we are dumping to disk in a clean way to read from this

**Comment by akshay-krishnan** [comment]
I think we can close this since we have the python visualizer you wrote. We can create more issues to track improvements to this and the javascript visualizer.

**Comment by johnwlambert** [comment]
Agreed, we have a working solution for now. Of course, it could be better, but we would want to describe how it should be better.
