### ISSUE TITLE
Evaluating GTSfM Performance on Datasets with Extreme Baselines

### ISSUE THREAD

**Issue by jytime** [borglab/gtsfm#762]
Hi all,

I am quite impressed by the remarkable work you've done with GTSfM. It's encouraging to see the continuous advancements in the field of global SfM.

I am curious to know if you have tested the method on more specialized datasets. Specifically, I'm interested in the performance on small-baseline datasets (like [IMC phototourism](https://www.cs.ubc.ca/research/image-matching-challenge/2021/data/)) and wide-baseline datasets (such as [Co3D](https://github.com/facebookresearch/co3d)).

My hypothesis is that global SfM might perform better on small-baseline data due to potentially less noisy correspondences. As mentioned in the paper, "Without noise from ‘front-end’ measurements, we find global SfM is close to exact." Consequently, this could potentially narrow the performance gap when compared to incremental SfM. Does this align with your observations? I am considering trying global sfm methods on IMC challenge.  (I noticed there is a phototourism dataset Gendarmenmarkt reported in the paper,  while not with extreme baselines.)

Best,
Jianyuan

**Comment by travisdriver** [comment]
I would say that the Phototourism datasets we present in the paper constitute "extreme" baseline examples. The Co3D datasets seem to make an orbit around the surveyed object, which is similar to the motion in the presented Skydio dataset in the paper. Feel free to run our pipeline on the Co3D datasets and let us know how we do!
