### ISSUE TITLE
Can this be used in lieu of Colmap for gaussian splatting?

### ISSUE THREAD

**Issue by Bardo-Konrad** [borglab/gtsfm#793]
Does it produce the following structure necessary for gaussian splatting ( https://github.com/graphdeco-inria/gaussian-splatting )

```
<location>
|---images
|   |---<image 0>
|   |---<image 1>
|   |---...
|---sparse
    |---0
        |---cameras.bin
        |---images.bin
        |---points3D.bin
```

**Comment by travisdriver** [comment]
It will create files (i.e., cameras.txt, images.txt, points3D.txt) with the same format as the COLMAP outputs, which you can then put into any directory structure you like.
